version: '3.5'
services:
  media-api:
    build: .
    container_name: media.api
    command: bash -c "tail -f /dev/null"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    ports:
      - "3008:3008"
    networks:
      api:
        aliases:
          - media-api

  mongo:
    image: mongo:4
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - api

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    networks:
      - api

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    networks:
      - api

networks:
  api:
    name: api
    driver: bridge
