version: '3'
services:
  media-api:
    build: .
    container_name: media.api
    command: bash -c "tail -f /dev/null"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    ports:
      - "3008:3008"
    networks:
      - api

  mongo:
    image: mongo:4
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - api

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2

networks:
  api:
    driver: bridge
