openapi: 3.0.0
servers:
  - description: Media-network api localhost servers
    url: http://localhost:{port}
    variables:
      port:
        default: '3008'
info:
  description: Api for Secret Key
  version: '1.0.0'
  title: Media-network secret key api
components:
  securitySchemes:
    contentType:
      type: apiKey
      in: header
      name: Content-Type
    authorization:
      type: apiKey
      in: header
      name: Authorization
    accountAuthorization:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    SecretKey:
      type: object
      properties:
        key:
          type: string
        app:
          type: string
        title:
          type: string
        description:
          type: string
        isDeleted:
          type: boolean
paths:
  /secret-keys:
    get:
      summary: List secret keys.
      description: Return the list of secret keys.
      tags:
        - SecretKey
      security:
        - contentType: []
          authorization: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SecretKey'
    post:
      summary: Create secret key.
      description: Return created secret key info.
      tags:
        - SecretKey
      security:
        - contentType: []
          authorization: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                app:
                  type: string
                title:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecretKey'
  /secret-keys/{key}:
    get:
      summary: Get secret key.
      description: Return secret key info.
      tags:
        - SecretKey
      security:
        - contentType: []
          authorization: []
      parameters:
        - name: key
          in: path
          example: Z2hdALx
          required: true
          description: The secret key in path.
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecretKey'
        '404':
          description: NOT_FOUND
    delete:
      summary: Remove secret key.
      description: Remove secret key.
      tags:
        - SecretKey
      security:
        - contentType: []
          accountAuthorization: []
      parameters:
        - name: key
          in: path
          example: Z2hdALx
          required: true
          description: The secret key in path.
          schema:
            type: string
      responses:
        '204':
          description: NO_CONTENT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecretKey'
        '403':
          description: FORBIDDEN
